### PR TITLE
refactor(livegain,sdk): refactor plugin initilialization

### PR DESCRIPTION
**Pull request by hugomallet**
remove ready getter and move state params initialization to initialize method

### CODE REVIEW

**Comment by Fr0stbyteR** [comment]
`static createInstance()` is not adapted. (What's the correct way to construct? Is there any use case to call `constructor()` and `initialize()` separately and manually instead of `static createInstance()`?)

**Comment by hugomallet** [comment]
What do you mean by not adapted ? No i don't think there any use case to call them separately. I did this because polymophirsm issue. Do you have a better idea ?

**Comment by Fr0stbyteR** [comment]
OK I did a commit to fix createInstance.
So it means I can declare in ts that the `constructor()` and `initialize()` are `protected` or even `private` ?

**Comment by hugomallet** [comment]
We can let them public ? There is no real problem of calling them separately

**Pull request merged**
